### ISSUE TITLE
GPU instances not showing in "IAM/Quotas"

### ISSUE THREAD

**Issue by ColasGael** [cs231n/gcloud#1]
Hi,

If you do not select a default "region" and "zone" in "Compute Engine/Parameters", the GPU quotas will not show up in "IAM/Quotas".

As this is not indicated in the StackOverflow thread, maybe you should add this in the "Request an increase in GPU quota" part of the tutorial.
In case some students face the same issue.

Thanks!

**Comment by ColasGael** [comment]
Also, to be able to increase the Quotas, you need to "upgrade your account from a free trial".

Finally, you need to increase both the instance limit: "NVIDIA K80 GPUs" for example (StackOverflow tutorial) and the global limit of GPU "GPUs (all region)"

**Comment by DrJimFan** [comment]
Thanks for the notes. I'll update the tutorial accordingly.
